---
- name:                 "Verifiy if Profile already exists"
  stat:
    path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
  register:             profile_already_exists

- name:                 "Generate Response file"
  template:
    src:                "{{ __tpl_file }}"
    dest:               "{{ __rsp_file }}"
  when:                 profile_already_exists.stat.exists == true

- name:                 "Configure LDAP"
  command:
    chdir={{ __bin_dir }}
    {{ __bin_dir }}/wsadmin.sh -lang jython -port 8879 -username {{ __was_username }} -password {{ __was_password }} -f {{ __rsp_file }}
  register:             cout
  changed_when:         cout.rc == 0
  #changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
  when:                 profile_already_exists.stat.exists == true
