# Install WebSphere Application Server - Network Deployment
#
# Variables used in this playbook that can be setup at hosts file.
#
# HTTP server that has installation Files
#   was_repository_url:     http://192.168.1.1/was/8.5.5
#
#    __was_files:
#      - bf:                WAS_ND_V8.5.5_1_OF_3.zip
#        bfs:               b1333962ba4b25c8632c7e4c82b472350337e99febac8f70ffbd551ca3905e83
#      - { bf: WAS_ND_V8.5.5_2_OF_3.zip, bfs: 440b7ed82089d43b1d45c1e908bf0a1951fed98f2542b6d37c8b5e7274c6b1c9 }
#      - { bf: WAS_ND_V8.5.5_3_OF_3.zip, bfs: b73ae070656bed6399a113c2db9fb0abaf5505b0d41c564bf2a58ce0b1e0dcd2 }
#    __this_version:        "{{ was_version | default('8.5.5000.20130514_1044') }}"
---
- hosts:                    dmgr,was-servers
  become:                   true
  vars:
    #tmp_dir:              "/opt/IBM/Binaries/was"
    #iim_install_location: "/opt/IBM/InstallationManager"
    #was_install_location: "/opt/IBM/WebSphere/AppServer"
    #imshared_location:    "/opt/IBM/IMShared"
    #__was_files:
    #  - { bf: WAS_ND_V8.5.5_1_OF_3.zip, bfs: b1333962ba4b25c8632c7e4c82b472350337e99febac8f70ffbd551ca3905e83 }
    #  - { bf: WAS_ND_V8.5.5_2_OF_3.zip, bfs: 440b7ed82089d43b1d45c1e908bf0a1951fed98f2542b6d37c8b5e7274c6b1c9 }
    #  - { bf: WAS_ND_V8.5.5_3_OF_3.zip, bfs: b73ae070656bed6399a113c2db9fb0abaf5505b0d41c564bf2a58ce0b1e0dcd2 }
    #was_version: "8.5.5000.20130514_1044"
  roles:
    - roles/was-nd-install
