# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-create-dmgr-profile.yml
#
---
- name:                     Create Deployment Manager Profile
  hosts:                    dmgr
  become:                   true
  vars:
    #__profile_name:         "{{ profile_name | default('Dmgr01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    #__was_nodename:         "{{ was_nodename }}"
    #__was_cellname:         "{{ was_cellname }}"
    #__was_hostname:         "{{ inventory_hostname }}"
    #__was_username:         "{{ was_username }}"
    #__was_password:         "{{ was_password }}"
  roles:
    - was-create-dmgr-profile
