# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-server-start.yml
#
---
- name:                     "Add TLS Signer Certificate for AD to Cell Default Trust Store"
  hosts:                    dmgr
  become:                   true
  vars:
    #__profile_name:         "{{ profile_name | default('Dmgr01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    #__was_username:         "{{ was_username }}"
    #__was_password:         "{{ was_password }}"
    #__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    #__bin_dir:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin"
    #__rsp_file:             "{{ __bin_dir }}/was_import_tls_cert.py"
    #__tpl_file:             "was_import_tls_cert.py.j2"
  roles:
    - was-import-tls-cert
    
