# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-server-start.yml
#
---
- name:                     "Add Configure LDAP Repository"
  hosts:                    dmgr
  become:                   true
  vars:
    #__profile_name:         "{{ profile_name | default('Dmgr01') }}"
    #__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    #__was_nodename:         "{{ was_nodename }}"
    #__was_username:         "{{ was_username }}"
    #__was_password:         "{{ was_password }}"

  roles:
    - was-config-ldap
    
