---
- name:              Is Product already Installed?
  command:           "egrep {{ __product_id }} /var/ibm/InstallationManager/installed.xml"
  register:          version_already_installed
  ignore_errors:     true

- name:              "Use Fix Pack 6.0.3 CR3?"
  set_fact:
    __cnx_fixes_files: "{{ __cnx_fixes_files_cr3 }}"
    __version_check:   "Updated to com.ibm.connections{{ __cnx_fixes_version }}"
    __product_id:      "\"id='com.ibm.connections' version='{{ __cnx_fixes_version }}'\""
  when:              ( __cnx_fixes_version == __cnx_fixes_version_cr3 )