---
- name:              Encode WAS Password
  command:           "{{ __iim_install_location }}/eclipse/tools/imutilsc encryptString {{ was_password }}"
  register:          __was_encoded_password
  changed_when:      ( __was_encoded_password.rc == 0)

- name:              Encode DB Passwords
  command:           "{{ __iim_install_location }}/eclipse/tools/imutilsc encryptString {{ item.pw }}"
  register:          __cnx_db_info_results
  #changed_when:      ( item.encoded_pw.rc == 0)
  with_items:        "{{ __cnx_db_info }}"

- name:              Encode CCM Password 
  command:           "{{ __iim_install_location }}/eclipse/tools/imutilsc encryptString {{ was_password }}"
  register:          __ccm_encoded_password
  changed_when:      ( __ccm_encoded_password.rc == 0)
  when:              ( ccm_install is defined )

- name:              Encode DB Passwords for CCM
  command:           "{{ __iim_install_location }}/eclipse/tools/imutilsc encryptString {{ item.pw }}"
  register:          __ccm_db_info_results
  with_items:        "{{ __ccm_db_info }}"
  when:              ( ccm_install is defined )

- name:              Generate Response file
  template:
    src:             "{{ __tpl_file }}"
    dest:            "{{ __rsp_file }}"

- name:              Disable Repository on Installation Manager
  replace:
    path:            /var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
    regexp:          '(\s*)RepositoryIsOpen=true(\s*)'
    replace:         '\1RepositoryIsOpen=false\2'
    backup:          yes
  ignore_errors:     true

- name:              Install Connections Software
  command:
    chdir={{ __tmp_dir }}
    {{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}
  register:          cout
#  changed_when:      ( cout.stdout.find(__version_check) != -1)
#
##- debug:            var=cout
#
#- name:              Cleanup Binaries directory
#  file:
#    state:           absent
#    path:            "{{ __tmp_dir }}"
