---
#- name:         show the groups the host(s) are in
#  debug:        msg="{{group_names}}"
- name:          Check Vars
  include_tasks: check_vars.yml

- name:          Setup Operating System
  include_tasks: setup_os.yml

- name:          Define Vars
  include_tasks: define_vars.yml

#- include_tasks: generate_response_file.yml

- include_tasks: install_connections.yml
  when:          version_already_installed.rc != 0


