---
__repository_url:       "{{ ihs_repository_url }}"
__tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}/wassup_fixes"
__logs_dir:             "{{ tmp_dir | default('/opt/IBM/Binaries') }}/logs"
__iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
__ihs_install_location: "{{ ihs_install_location  | default('/opt/IBM/HTTPServer') }}"
__plg_install_location: "{{ plg_install_location  | default('/opt/IBM/WebSphere/Plugins') }}"
__wct_install_location: "{{ wct_install_location  | default('/opt/IBM/WebSphere/Toolbox') }}"
__imshared_location:    "{{ imshared_location  | default('/opt/IBM/IMShared') }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/ihs_plg_wct_fixes.rsp"
__log_file:             "{{ __logs_dir }}/ihs_fixes_install.{{ __now }}.log"
__tpl_file:             "ihs_plg_wct_fixes.rsp.j2"

__this_version:         "{{ ihs_version | default('8.5.5011.20161206_1434') }}"
__this_files:
  - { bf: 8.5.5-WS-WASSupplements-FP011-part1.zip, bfs: 4a8f560c3b546321a7e67facc5c25255ecd11c6b29e3fed0a38f203dd339a771 }
  - { bf: 8.5.5-WS-WASSupplements-FP011-part2.zip, bfs: 6fec8b763020c72693a5a98ecba37c5f7778ab9bcf44b7089a9edb3dc51cb84c }
  - { bf: 8.5.5-WS-WASSupplements-FP011-part3.zip, bfs: fe0cbc3ad678c21bb43c588bcc80242d8556b80ca2f4c237e5cc97b271eeffc7 }
__version_check:        "Updated to com.ibm.websphere.IHS.v85_{{ __this_version }}"
__product_id:           "\"id='com.ibm.websphere.IHS.v85' version='{{ __this_version }}'\""

__ihs_version_fp9:      "8.5.5009.20160225_0435"
__ihs_files_fp9:
  - { bf: 8.5.5-WS-WASSupplements-FP0000009-part1.zip, bfs: 736b3e13b3f38289aee4367c62b19ffcea06cf2ae4058fdb0197a3e1ec07fb27 }
  - { bf: 8.5.5-WS-WASSupplements-FP0000009-part2.zip, bfs: 1728f184c38306e86e2e4102f153008f3b38af5c98089324b0fa4921affa2c2e }


__iim_product_id:       "\"id='com.ibm.cic.agent\""
__ihs_product_id:       "\"id='com.ibm.websphere.IHS.v85'\""
