---
- name:                 "Verifiy if Profile already exists"
  stat:
    path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
  register:             profile_already_exists

- name:                 "Generate Response file"
  template:
    src:                "{{ __tpl_file }}"
    dest:               "{{ __rsp_file }}"
  when:                 profile_already_exists.stat.exists != true

- name:                 "Create Was Profile"
  command:              "{{ __was_install_location }}/bin/manageprofiles.sh -response {{ __rsp_file }}"
  register:             cout
  changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
  when:                 profile_already_exists.stat.exists != true
