# Install Installation Manager
#
# Variables used in this playbook that can be setup at hosts file.
#
# HTTP server that has installation Files
#   iim_repository_url:    http://172.17.202.237/installation
#
# For 1.8.6000
#   iim_bin_file=agent.installer.linux.gtk.x86_64_1.8.6000.20161118_1611.zip
#   iim_bin_file_sha256=b253a06bccace5934b108632487182f6a6f659082fea69372242b9865a64e4f3
#
# For 1.8.4001
#  iim_bin_file=agent.installer.linux.gtk.x86_64_1.8.4001.20160217_1716.zip
#  iim_bin_file_sha256=c1cab8bf2c4c2d15f350fc4c7a564c248acc3227a5705406f9d94e6e0f108555
---
- name:                     Install IBM Installation Manager
  hosts:                    was-servers
  become:                   true
  vars:
    __tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}/iim"
    __logs_dir:             "{{ tmp_dir | default('/opt/IBM/Binaries') }}/logs"
    __iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
  tasks:
    - name:                 Install pre-requisites
      yum:                  name={{item}} state=present
      with_items:
        - unzip
        - tar
        - wget
      when:                 (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS")

    - name:                 Check Variables
      debug:
        msg="iim_repository_url={{ iim_repository_url }} iim_bin_file={{ iim_bin_file }} iim_bin_file_sha256={{ iim_bin_file_sha256 }}"

    - name:                 Create Binaries directory
      file:                 path={{ __tmp_dir }} state=directory mode=0755

    - name:                 Create Logs directory
      file:                 path={{ __logs_dir }} state=directory mode=0755

    - name:                 Download IBM Installation Manager
      get_url:
        url:                "{{ iim_repository_url }}/{{ iim_bin_file }}"
        dest:               "{{ __tmp_dir }}/{{ iim_bin_file }}"
        mode:               0755
        checksum:           sha256:{{ iim_bin_file_sha256 }}

    - name:                 Extract IBM Installation Manager
      unarchive:
        src:                "{{ __tmp_dir }}/{{ iim_bin_file }}"
        dest:               "{{ __tmp_dir }}/"
        copy:               no

    #- name:                My debug
    #  debug:               msg="{{ __tmp_dir }}/tools/imcl install com.ibm.cic.agent -acceptLicense -installationDirectory {{ __iim_install_location }} -repositories {{ __tmp_dir }} -log {{ __tmp_dir }}/iim_install.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.log"

    - name:                 Install/Update IBM Installation Manager
      command:
        chdir={{ __tmp_dir }}
        {{ __tmp_dir }}/tools/imcl install com.ibm.cic.agent -acceptLicense -installationDirectory {{ __iim_install_location }} -repositories {{ __tmp_dir }} -log {{ __logs_dir }}/iim_install.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.log
        creates={{ __iim_install_location }}
      register:             install
      changed_when:         install.rc != 0

    - name:                 Cleanup Binaries directory
      file:
        state:              absent
        path:               "{{ __tmp_dir }}"
