# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-create-dmgr-profile.yml
#
---
- name:                     Create Deployment Manager Profile
  hosts:                    dmgr
  become:                   true
  vars:
    __profile_name:         "{{ profile_name | default('Dmgr01') }}"
    __was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    __was_nodename:         "{{ was_nodename }}"
    __was_cellname:         "{{ was_cellname }}"
    __was_hostname:         "{{ inventory_hostname }}"
    __was_username:         "{{ was_username }}"
    __was_password:         "{{ was_password }}"
    __now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    __logs_dir:             "{{ __was_install_location }}/logs"
    __rsp_file:             "{{ __logs_dir }}/was_profile_dmgr.rsp"
    __tpl_file:             "was_profile_dmgr.rsp.j2"
  tasks:
    - name:                 "Verifiy if Profile already exists"
      stat:
        path:               "{{ __was_install_location }}/profiles/{{ __profile_name }}"
      register:             profile_already_exists

    - name:                 "Generate Response file"
      template:
        src:                "{{ __tpl_file }}"
        dest:               "{{ __rsp_file }}"
      when:                 profile_already_exists.stat.exists != true

    - name:                 "Create Was Profile"
      command:              "{{ __was_install_location }}/bin/manageprofiles.sh -response {{ __rsp_file }}"
      register:             cout
      changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)
      when:                 profile_already_exists.stat.exists != true
