# How to Run
#
# ansible-playbook -i hosts.development -k ansible-ibm-websphere/playbooks/was-create-dmgr-profile.yml
#
---
- name:                     DeleteAll WAS Profile
  hosts:                    was-servers
  become:                   true
  vars:
    __profile_name:         "{{ profile_name | default('AppSrv01') }}"
    __was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
  tasks:

    - name:                 "Delete WAS Profile"
      command:              "{{ __was_install_location }}/bin/manageprofiles.sh -deleteAll"
      register:             cout
      changed_when:         ( cout.stdout.find('INSTCONFSUCCESS') != -1)

    - name:                  "Cleanup Profiles directories"
      file:
        path:                "{{ __was_install_location }}/profiles"
        state:               absent
