# How to Run
#
# ansible-playbooks -i hosts.development -k ansible-ibm-websphere/playbooks/was-server-start.yml
#
---
- name:                     Stop WAS Servers
  hosts:                    was-servers
  serial:                   1  # run sequentially
  become:                   true
  vars:
    __profile_name:         "{{ profile_name | default('AppSrv01') }}"
    __was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
    __servers:              "{{ servers }}"
  tasks:
    - name:                 "Verify if pid file"
      shell:                ps -p `cat "{{ __was_install_location }}/profiles/{{ __profile_name }}/logs/{{ item }}/{{ item }}.pid"`
      register:             server_is_running
      ignore_errors:        true
      with_items:           "{{ __servers }}"

    #- debug: var=server_is_running
    - name:                 "Stop Servers"
      command:              "{{ __was_install_location }}/profiles/{{ __profile_name }}/bin/stopServer.sh {{ item.item }} -username {{ was_username }} -password {{ was_password }}"
      register:             cout
      changed_when:         cout.rc == 0
      when:                 item.rc == 0
      with_items:           "{{ server_is_running.results }}"
